# Generated by Django 5.1.4 on 2025-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
