# Generated by Django 5.1.4 on 2025-01-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_borrower_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Electronics', 'Electronics'), ('Stationary', 'Stationary')], default='Stationary', max_length=50),
            preserve_default=False,
        ),
    ]
